Todo_App/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("index.urls"))
]

index/urls.py
from django.urls import path

from index import views

app_name = 'todo'
urlpatterns = [

    path('', views.task_list, name='list'),
    path('addlist/', views.addlist, name="addlist"),
    path('completed/<str:pk>/', views.taskComplete, name='completed'),
    path('task_delete/<str:pk>/', views.taskDelete, name='delete')
]

index/models.py
from django.db import models


# Create your models here.
class Todo_App(models.Model):
    title = models.CharField(max_length=150, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    Task_done = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_done =models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

index/views.py
from django.shortcuts import render, redirect

# Create your views here.
from index.form import TodoForm
from index.models import Todo_App


def task_list(request):
    form = TodoForm
    task = Todo_App.objects.all().order_by('-date_created')

    context = {'form': form, 'tasks': task}
    return render(request, 'index/task_list.html', context)


def addlist(request):
    form = TodoForm()
    if request.method == "POST":
        form = TodoForm(request.POST)
    if form.is_valid:
        form.save()
        return redirect('todo:list')


def taskComplete(request, pk):
    task = Todo_App.objects.get(id=pk)

    task.Task_done = True
    if task:
        task.save()

    return redirect('todo:list')


def taskDelete(request, pk):
    task = Todo_App.objects.get(id=pk)
    task.delete()
    return redirect('todo:list')

index/templates/index/task_confirm_delete.html
<p>Are you sure you want to delete "{{item}}"?</p>

<a href="{% url 'list' %}" >Cancel</a>

<form method="POST" action="">
	{% csrf_token %}
	<input type="submit" name="Confirm">
</form>

index/templates/index/task_list.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

	body{
		background-color: #638CB8;
	}

	input{
		width: 100%;
		padding: 12px 20px;
		margin: 8px 0;
		box-sizing: border-box;
	}

	input::placeholder {
	  color: #d3d3d3;
	}

	.submit{
		background-color: #6BA3E8;
	}

	.center-column{
		width:600px;
		margin: 20px auto;
		padding:20px;
		background-color: #fff;
		border-radius: 3px;

		overflow: auto ;
		box-shadow: 6px 2px 30px 0px rgba(0,0,0,0.75);

	}

	.item-row{
		background-color: #906abd;
		margin: 10px;
		padding: 20px;
		border-radius: 3px;
		color: #fff;
		font-size: 16px;

		box-shadow: 0px -1px 10px -4px rgba(0,0,0,0.75);
	}

	.btn-danger{
		background-color: #ffae19;
		border-color: #e59400;
	}

</style>

<div class="center-column">

	<form method="POST" action="{% url 'todo:addlist' %}">
		{% csrf_token %}
		<span>Task</span>{{form.title}}
		<input class="btn btn-info" type="submit" name="Create Task">
	</form>

	<div class="todo-list">
		{% if tasks %}
		<h3 class="item-row text-center">My Tasks to do</h3>
		{% else%}
		<h3 class="item-row text-center">No Task Available</h3>
		{% endif %}

	{% for task in tasks %}
		<div class="item-row">



			{% if task.Task_done == True %}
			<span>created : {{task.date_created|timesince}} ago</span>&nbsp;<br><br>&nbsp;
			<strike>{{task}} :</strike>&nbsp;<br><br>
			<span>completed: {{task.date_done|timesince}} ago</span><br><br>


					<a class="btn btn-sm btn-danger" href="{% url 'todo:delete' task.id %}">Delete</a>

			     {% else %}
						<br>
						<h6>created : {{task.date_created|timesince}} ago</h6>
						&nbsp;<span>{{task}}:</span><br><br>
					&nbsp;<a class="btn btn-sm btn-info" href="{% url 'todo:completed' task.id %}">Done</a>&nbsp;
					<a class="btn btn-sm btn-danger" href="{% url 'todo:delete' task.id %}">Delete</a>









			{% endif %}
		</div>
	{% endfor %}
	</div>

</div>

index/templates/index/update_task.html
<h3>Update Task</h3>

<form method="POST" action="">
	{% csrf_token %}

	{{form}}
	<input type="submit" name="Update Task">
	
	
</form>